# Generated by Django 3.0.4 on 2020-04-20 02:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0003_auto_20200420_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 2, 33, 12, 582638, tzinfo=utc)),
        ),
    ]
