# Generated by Django 3.0.4 on 2020-04-20 01:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200420_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesstasklist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='todo'),
        ),
        migrations.AlterField(
            model_name='businesstask',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 23, 1, 47, 0, 660593, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='taskbase',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 20, 1, 47, 0, 660188, tzinfo=utc)),
        ),
    ]
