# Generated by Django 3.0.4 on 2020-04-20 02:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200420_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='businesstask',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 23, 2, 33, 12, 586228, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='taskbase',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 20, 2, 33, 12, 585833, tzinfo=utc)),
        ),
    ]
