# Generated by Django 3.0.4 on 2020-04-16 05:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0003_auto_20200416_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 5, 28, 11, 849212, tzinfo=utc)),
        ),
    ]
