# Generated by Django 3.0.4 on 2020-04-20 05:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiverSignal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TaskBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[(1, 'done'), (2, 'pending'), (3, 'not started')], default=3, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalTaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal Task List',
                'verbose_name_plural': 'Personal Task Lists',
            },
        ),
        migrations.CreateModel(
            name='BusinessTaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='todo')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Task List',
                'verbose_name_plural': 'Business Task Lists',
            },
        ),
        migrations.CreateModel(
            name='PersonalTask',
            fields=[
                ('taskbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.TaskBase')),
                ('image', models.ImageField(blank=True, null=True, upload_to='todo')),
                ('task_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PersonalTaskList')),
            ],
            bases=('main.taskbase',),
        ),
        migrations.CreateModel(
            name='BusinessTask',
            fields=[
                ('taskbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.TaskBase')),
                ('priority', models.IntegerField(default=0)),
                ('due_date', models.DateTimeField(default=datetime.datetime(2020, 4, 23, 5, 3, 1, 102599))),
                ('task_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.BusinessTaskList')),
            ],
            bases=('main.taskbase',),
        ),
    ]
