# Generated by Django 3.0.4 on 2020-04-20 01:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltask',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='todo'),
        ),
        migrations.AlterField(
            model_name='businesstask',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 23, 1, 44, 18, 537562, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='taskbase',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 20, 1, 44, 18, 537243, tzinfo=utc)),
        ),
    ]
